---
title: Political Leadership Survival in the Aftermath of Coups or Overstays
format:
  pdf:
    keep-tex: true  
    linestretch: 1.75
    papersize: A4
    indent: true
    
    number-sections: true
    keywords: [Political survival, Coups, Overstays]

date: last-modified
author:
  - name: Zhu Qi
  - affiliations: Department of Government, University of Essex
      # - name: University of Essex
      #   department: Department of Government
  
abstract: |
 **Abstract:** This study endeavors to conduct an in-depth analysis of the determinants impacting the survival of political leadership that has ascended to power, either through coups or overstays. Utilizing a survival model, the research investigates the influence of factors such as political stability, military control, economic performance, external alliances, regime types, and levels of democracy on the endurance of political leaders. Employing a quantitative approach with a novel dataset encompassing coups and overstays, this research makes a significant contribution to existing literature by providing valuable insights into the factors shaping political survival for leaders who assume office or maintain power through unconstitutional means.

bibliography: survival.bib
link-citations: true
fontsize: 12pt
execute: 
  freeze: auto
---

## Introduction

In political science, a compelling enigma persists: why do certain leaders manage to cling to power for three or four decades, while others find their tenures cut short after just several years, or even mere months or days? This intriguing question has been extensively explored in numerous existing works [@clinton1975politics, @buenodemesquita2003]. Some of these works encompass leaders across diverse political landscapes, spanning democracies and autocracies, parliamentary and presidential systems, as well as civilian and military contexts [@buenodemesquita2003]. Others narrow their focus to specific types of regimes, delving into democracies [@svolik2014] or autocracies [@davenport2021].

However, a significant number of political leaders, particularly in democracies and some in autocracies, undergo regular and predictable tenures. A prime example is found in the United States, where presidents may stay in the White House for up to eight years if they perform well and secure a second term. Even in cases of poor performance, they typically complete a full four-year term. Another illustration can be drawn from autocratic Mexico between 1919 and 2000, where each president served a fixed six-year term without facing overthrows or overstays. In such scenarios, analyzing the survival of these leaders seems futile, as power transitions from one political leader to the next are typically observed within the framework of constitutional rules or unwritten conventions.

The central emphasis on political longevity centers around leaders who stay in power for unforeseen durations. In theory, such situations can happen in any political context. Even in the United States, one of the most regular power transition countries, President Trump, following his electoral defeat, endeavoured to extend his tenure by contesting the outcome of the general election. However, the predominant instances of unexpected political tenures revolve around leaders who either seize power through coups or overstay through unconstitutional means---this constitutes the core focus of this paper.

The analysis of their tenures is particularly significant for two reasons. Firstly, the durations of these leaders' tenures exhibit considerable variation, ranging from mere months to several decades. Secondly, predicting the tenures of such leaders proves challenging. A seemingly robust and stable regime can collapse suddenly overnight, while an apparently fragile one might persist for decades. The substantial disparities in these tenures remain inadequately explained, posing a perplexing challenge and attracting the attention of numerous political scientists.

Building upon discussions surrounding coups and incumbent overstays, this paper delves into the trajectories of political leaders who ascended to power through coups or overstayed their intended terms. The primary focus lies in unravelling the duration of these leaders' tenures and understanding the underlying determinants.

## Theories

The survival of political leaders following coups or overstays may hinge on six pivotal factors:

### Coups vs. overstays

Survival in power relies significantly on the cohesion of the ruling group. As numerous scholars have pointed out, internal conflicts among elites pose a more serious threat to the stability of those in power. Coups often lay bare the fractures within a regime, not only attracting more followers to orchestrate new coups but also emboldening external challengers, including uprisings, revolutions, and civil wars. On the other hand, successful tenures unmistakably showcase the incumbents' firm grasp on power, discouraging both internal dissent and external threats [@dahl2023].

**Hypothesis 1 (H1):** Political leaders who successfully extend their time in power are more likely to have prolonged survival compared to leaders who assume power through coups.

### Regime types

In the majority of cases, regimes following coups or prolonged stays tend to be non-democratic. Democratic leaders are generally anticipated to relinquish power in a regular and cyclical manner. Conversely, for non-democratic leaders, the duration of their tenures is heavily influenced by the type of autocracy. The three primary autocratic regimes are dominant party, military, and personal.

Within the military regime, leaders often encounter more challenges during their tenures. The ability to challenge incumbents, particularly those within ruling groups, relies significantly on the support of military forces. In dominant party or personal regimes, the military typically operates under the control of party or personal leaders, who are the incumbents themselves. Unlike military regimes, where generals often play significant roles in politics, there are typically many generals in dominant party or personal regimes, acting as checks and balances on each other. Military regimes, however, with their powerful army leaders and more influential generals, are more prone to political interference and internal conflicts, leading to shorter tenures for leaders in such regimes.

Hypothesis 2 (H2): Leaders in dominant party or personal regimes are expected to have longer survival periods than those in military regimes.

### Societal stability

**Hypothesis 3 (H3):** Political leaders presiding over stable societies are likely to experience longer tenures.

### Purges and repressions

**Hypothesis 4 (H4):** Leaders who are more prone to employ stringent repression against dissidents are expected to have longer survival durations.

### External alliances

**Hypothesis 5 (H5):** Leaders with strong external alliances are anticipated to have extended survival periods.

### Economic performance

**Hypothesis 6 (H6):** Leaders with a robust economic performance are likely to endure longer than their counterparts facing economic crises.

\newpage

## References
