## Setup

```{r}
#| label: setup
library(tidyverse)
library(readxl)
library(data.table)
library(survival)

library(haven)
library(vdemdata)
library(democracyData)
library(janitor)
library(gtsummary)
library(zoo)
library(survminer)
library(kableExtra)
library(jtools)
```

$$
Surv(\text{survival_time}, status) = group + 
GDP_\text{growth_trend} + GDP_\text{pc_log} + 
pop_{log} + polity5 + polstab + age$$

## overstays

```{r}
#| label: overstays
# coups <- fread("powell_thyne_coups_final.txt") %>%
#   filter(coup==2) %>%
#   mutate(startdate=ymd(paste(year,month,day)),
#          joindate=interval(startdate - days(1), startdate + days(1))
# ) %>%
#   select(-c(3,4,9))

overstays <- read_excel("data/self_coup_Reddy.xlsx") %>%
  filter(Success == 1) %>%
  select(ccode, ruler, starty, sdate, endy, edate, overstay_year = year) |> 
  mutate(overstay_date = make_date(overstay_year, month(sdate), day(sdate)))
str(overstays)
```

## leaders

```{r}
#| label: PLAD

PLAD <- read_excel("../PLAD/PLAD_April_2024.xls")
plad <- PLAD |> 
  select(1:6, entry, exit, gender, yrborn, birthdate) |>
  mutate(startdate = dmy(startdate),
         birthdate = dmy(birthdate),
         enddate = case_when(exit == "Still in Office" ~ Sys.Date(),
                             .default = dmy(enddate)),
         yrborn = as.numeric(yrborn)
         ) |> 
  filter(enddate - startdate > 270)

str(KSG)
str(plad)
```

```{r}
KSG<- fread("http://ksgleditsch.com/data/1March_Archigos_4.1.txt", encoding = "Latin-1") |> 
  mutate(startdate = ymd(startdate),
         enddate = ymd(enddate),
         borndate = ymd(borndate)) |> 
  filter(enddate > "1945-01-01",
         enddate - startdate > 270) 


KSG |> 
  full_join(plad, by = c("idacr", "startdate")) |>
  mutate(obsid = coalesce(obsid, plad_id),
         leader.x = coalesce(leader.x, leader.y),
         enddate.x = if_else(is.na(enddate.x) | exit.x == "Still in Office", enddate.y, enddate.x),
         entry.x = coalesce(entry.x, entry.y),
         exit.x = if_else(exit.x == "Still in Office" | is.na(exit.x), exit.y, exit.x),
         exitcode = if_else(exitcode == "Still in Office" | is.na(exitcode), exit.y, exitcode),
         gender.x = coalesce(gender.x, gender.y),
         yrborn.x = coalesce(yrborn.x, yrborn.y),
         borndate = coalesce(borndate, birthdate)) |> 
  group_by(idacr) |>
  fill(ccode) |>
  ungroup() |>
  view()

str(plad)
```

# update "still in office"

```{r}
leaders$enddate[leaders$leader=="Nguema Mbasogo"] <- "2023-11-27"

leaders$enddate[leaders$leader=="Rakhmonov"] <- "2023-11-27"

leaders$enddate[leaders$leader=="Erdogan"] <- "2023-11-27"

leaders$enddate[leaders$leader=="Afeworki"] <- "2023-11-27"

leaders$enddate[leaders$leader=="Guelleh"] <- "2023-11-27"

leaders$enddate[leaders$leader=="Paul Kagame"] <- "2023-11-27"

leaders$enddate[leaders$leader=="Xi Jinping"] <- "2023-11-27"

leaders$enddate[leaders$leader=="Museveni"] <- "2023-11-27"

leaders$enddate[leaders$leader=="Nguesso"] <- "2023-11-27"

leaders$enddate[leaders$leader=="Biya"] <- "2023-11-27"

leaders$endy[leaders$leader=="Nguema Mbasogo"] <- "2023-11-27"


leaders$enddate[leaders$leader=="Ilhma Aliyev"] <- "2023-11-27"


leaders$enddate[leaders$leader=="Lukashenko"] <- "2023-11-27"

leaders$enddate[leaders$leader=="Putin"] <- "2023-11-27"

leaders$enddate[leaders$leader=="Daniel Ortega"] <- "2023-11-27"

leaders$enddate[leaders$leader=="Faure Gnassingbe"] <- "2023-11-27"


## Update step down after 2015-12-31
leaders$enddate[leaders$leader=="Nazarbayev"] <- "2019-3-20"
leaders$exit[leaders$leader=="Nazarbayev"] <- "Regular"


leaders$enddate[leaders$leader=="Karimov"] <- "2016-9-2"
leaders$exit[leaders$leader=="Karimov"] <- "Regular"

leaders$enddate[leaders$leader=="Qabus Bin Said"] <- "2020-1-10"
leaders$exit[leaders$leader=="Qabus Bin Said"] <- "Regular"

leaders$enddate[leaders$leader=="Dos Santos"] <- "2017-9-25"
leaders$exit[leaders$leader=="Dos Santos"] <- "Regular"

leaders$enddate[leaders$leader=="Al-Bashir"] <- "2019-4-11"
leaders$exit[leaders$leader=="Al-Bashir"] <- "Irregular"

leaders$enddate[leaders$leader=="Bouteflika"] <- "2019-4-2"
leaders$exit[leaders$leader=="Bouteflika"] <- "Irregular"

leaders$enddate[leaders$leader=="Mugabe"] <- "2017-11-21"
leaders$exit[leaders$leader=="Mugabe"] <- "Irregular"

leaders$enddate[leaders$leader=="Nkurunziza"] <- "2022-6-8"
leaders$exit[leaders$leader=="Nkurunziza"] <- "Regular"

leaders$enddate[leaders$leader=="Joseph Kabila"] <- "2019-1-24"
leaders$exit[leaders$leader=="Joseph Kabila"] <- "Regular"



leaders$enddate[leaders$leader=="Deby"] <- "2021-4-20"
leaders$exit[leaders$leader=="Deby"] <- "Irregular"



leaders$enddate[leaders$leader=="Conde"] <- "2021-9-5"
leaders$exit[leaders$leader=="Conde"] <- "Irregular"

leaders$enddate[leaders$leader=="Jammeh"] <- "2017-1-19"
leaders$exit[leaders$leader=="Jammeh"] <- "Irregular"


leaders$enddate[leaders$leader=="Petro Poroshenko"] <- "2019-5-20"
leaders$exit[leaders$leader=="Petro Poroshenko"] <- "Regular"


leaders$enddate[leaders$leader=="Juan Morales"] <- "2019-11-10"
leaders$exit[leaders$leader=="Juan Morales"] <- "Irregular"

leaders$enddate[leaders$leader=="Medina"] <- "2020-8-16"
leaders$exit[leaders$leader=="Medina"] <- "Regular"

leaders$enddate[leaders$leader=="Hernández"] <- "2022-1-27"
leaders$exit[leaders$leader=="Hernández"] <- "Regular"


leaders$enddate[leaders$leader=="Rafael Correa"] <- "2017-5-24"
leaders$exit[leaders$leader=="Rafael Correa"] <- "Regular"


leaders$enddate[leaders$leader=="Prayuth Chan-ocha"] <- "2023-8-22"
leaders$exit[leaders$leader=="Prayuth Chan-ocha"] <- "Regular"

leaders$enddate[leaders$leader=="Hun Sen"] <- "2023-8-22"
leaders$exit[leaders$leader=="Hun Sen"] <- "Regular"

leaders1 <- leaders %>%
  mutate(syear=year(startdate),
         eyear=year(enddate),
         last_irregular_exit = if_else(exit == "Irregular", enddate, 
                                       if_else(entry == "Irregular", startdate, NA))) %>%
  group_by(ccode) %>%
  fill(last_irregular_exit, 
       .direction = "down") %>%
  ungroup() |>
  filter(eyear > 1945) %>% 
  select(3:5,syear,eyear,6:10, yrborn, last_irregular_exit)

leaders2 <- leaders1 %>% 
  mutate(coup_exit=ifelse(exitcode %in% c("Removed by Military, without Foreign Support","Removed by Other Government Actors, without Foreign Support"),1,0),
         tenure = ymd(enddate) - ymd(startdate)) %>% 
  mutate(coup_entry=ifelse(lag(coup_exit==1),1,0),.by = ccode)
```

## leaders + overstays

```{r}
mydata <- leaders2 %>%
  left_join(overstays, join_by(ccode, syear == starty, eyear == endy)) %>%
  filter(!(is.na(ruler) & coup_entry == 0)) %>%
  select(leader, ruler, everything())
```

```{r}
mydata1 <- mydata %>%
  mutate(
    group = case_when(!is.na(overstay_year) ~ "A",
                      .default = "B"),
    survival_time = case_when(
      group == "A" ~ ymd(enddate) - overstay_date,
      .default = ymd(enddate) - ymd(startdate)
    )
  ) %>%
  mutate(status = case_when(
    exit %in% c(
      "Regular",
      "Natural Death",
      "Still in Office",
      "Retired Due to Ill Health"
    ) ~ 1,
    .default = 2
  ))


table(mydata1$group)
table(mydata1$exit)
table(mydata1$status)
```

```{r}
mydata2 <- mydata1 |>
  mutate(
    startdate = if_else(group == "A", ymd(overstay_date), ymd(startdate)),
    enddate = ymd(enddate),
    last_irregular_exit =ymd(last_irregular_exit),
    age = if_else(group == "B", syear - yrborn, overstay_year -
                   yrborn)
  ) |>
  select(ccode, idacr, startdate, enddate, last_irregular_exit, leader, age, group, survival_time, status) |>
  add_row(# add an observation for a new leader
    ccode = 552,
    idacr = "ZIM",
    startdate = ymd(20171124),
    enddate = ymd(20231127),
    last_irregular_exit = ymd(20171121),
    leader = "Emmerson Mnangagwa",
    age = 75,
    group = "B",
    survival_time = enddate - startdate,
    status = 1
  )  |> 
  filter(survival_time > 180 & survival_time < 18000) 

mydata2$last_irregular_exit[mydata2$leader=="Lukashenko"] <- "1991-09-18"
mydata2$last_irregular_exit[mydata2$leader=="Kekkonen"] <- "1944-08-04"
mydata2$last_irregular_exit[mydata2$leader=="Biya"] <- "1960-01-01"
mydata2$last_irregular_exit[mydata2$leader=="Gouled Aptidon"] <- "1977-06-27"
mydata2$last_irregular_exit[mydata2$leader=="Guelleh"] <- "1977-06-27"
mydata2$last_irregular_exit[mydata2$leader=="Afeworki"] <- "1993-05-24"
mydata2$last_irregular_exit[mydata2$leader=="Banda"] <- "1964-07-06"
mydata2$last_irregular_exit[mydata2$leader=="Nujoma"] <- "1990-03-21"
mydata2$last_irregular_exit[mydata2$leader=="EL Khoury"] <- "1943-11-22"
mydata2$last_irregular_exit[mydata2$leader=="Niyazov"] <- "1990-10-27"
mydata2$last_irregular_exit[mydata2$leader=="Karimov"] <- "1990-03-24"
mydata2$last_irregular_exit[mydata2$leader=="Nazarbayev"] <- "1990-04-24"


```

## mydata2A

```{r}
mydata2A <- mydata2 |> 
  mutate(tstart = as.numeric(year(startdate) + (startdate - floor_date(startdate, "year"))/365),
         tstop = as.numeric(year(enddate) + (enddate - floor_date(enddate, "year"))/365),
         year = year(startdate),
         .after = enddate) |>
  mutate(last_irregular_exit = if_else(last_irregular_exit == enddate, startdate, last_irregular_exit),
         time_to_irregular_exit = log(as.numeric(enddate - last_irregular_exit)))
```

## mydata3

```{r}
mydata3A <- mydata2 |>
  mutate(first_year = startdate,
         last_year = enddate) |>
  survSplit(Surv(year(startdate), year(enddate), status) ~ .,
            data = _,
            cut = 1945:2022,
            id = "id",
            ) |>
  mutate(tstart = if_else(is.na(tstart), tstop, tstart)) |> 
  mutate(T1 = 0,
         T2 = ifelse(row_number() == 1, ceiling_date(first_year, "year") - first_year, 0),
         T2 = first(T2) + 365 * (row_number() - 1),
         T1 = lag(T2, default = 0),
         T2 = ifelse(row_number() == n(), survival_time, T2),
         age = age + row_number() - 1,
         .by = id) 
```

## GDP & population

```{r}
# codebook |> 
#   view()
gdp <- vdem |> 
  select(ccode = COWcode, country = country_name, year, GDP_pc = e_gdppc, pop = e_pop) |>
  filter(year >= 1945)|> 
  # create a new variable for 5-year moving average of GDP growth
  mutate(GDP_trend = GDP_pc / lag(rollapply(GDP_pc, width = 5, FUN = mean,
                               align = 'right', fill = NA)),
         .by = c(ccode))


GDP <- gdp |> 
  mutate(pop_log = log(pop)) |>
  select(ccode, country, year, GDP_trend, GDP_pc, pop_log) |>
  drop_na() 
```

## Polity 5

```{r}
polity <- polity5 |> 
  select(ccode = polity_annual_ccode, year, polity) |>
  # if polity is less than -10, then replace it with its previous value
  mutate(polity5 = ifelse(polity < -10, NA, polity)) |>
  group_by(ccode) |>
  fill(polity5, .direction = "up") |>
  ungroup() |>
  filter(year >= 1945)
```

## Political Stability

```{r}
polstab <- read_excel("data/MEPVv2018.xls") |> 
  select(ccode, year, polstab= actotal)
```

## Merge data

```{r}
Mydata2A <- mydata2A |> 
  mutate(year = year(startdate)) |> 
  left_join(GDP, by = c("ccode", "year" = "year")) |> 
  left_join(polity, by = c("ccode", "year" = "year")) |>
  left_join(polstab, by = c("ccode", "year" = "year")) |>
  drop_na() |> 
  select(ccode, idacr, country, year, tstart, tstop, last_irregular_exit, leader, age, group, survival_time, status, GDP_trend, GDP_pc, pop_log, polity5, polstab)

m1 <- Mydata2A |> 
  mutate(group = factor(group, 
                        labels = c("Overstay leaders", "Coup-entry leaders"))) |>
  coxph(Surv(survival_time, status) ~ group + GDP_trend + GDP_pc + pop_log + polity5 + polstab + age, data = _) 

m1|>
  summary()
```

```{r}
Mydata3A <- mydata3A |>
  mutate(year = floor(tstart)) |>
  left_join(GDP, by = c("ccode", "tstart" = "year")) |>
  left_join(polity, by = c("ccode", "tstart" = "year")) |>
  left_join(polstab, by = c("ccode", "tstart" = "year")) |>
  drop_na() |>
  select(id, ccode, idacr, country, tstart, tstop, leader, age, group, survival_time, T1, T2, status, GDP_trend, GDP_pc, pop_log, polity5, polstab)

m2 <- Mydata3A |>
  mutate(group = factor(group, 
                        labels = c("Overstay leaders", "Coup-entry leaders"))) |>
coxph(Surv(T1, T2, status) ~ group + GDP_trend+ GDP_pc + pop_log + polity5 + polstab + age + cluster(id), data = _)

summary(m2)
```

## Write to csv

```{r}
write.csv(Mydata2A, "mydata1.csv")
write.csv(Mydata3A, "mydata2.csv")
getwd()
```

```{r}
export_summs(m1, m2)
```

```{r}
read.csv("data/CCP.csv") |> 
  view()
```
